### ISSUE TITLE
I urgently need your help

### ISSUE THREAD

**Issue by 1zmm** [machines-in-motion/reactive_planners#16]
Hello, author, I'm using your code to run a simulation. I urgently need your help. I sincerely hope you can give me some tips on the following questions:

1. Is this code executed on Linux system or windows?

2. Do we need to download ROS?

3. Why is there no file generated after colon build?

Looking forward to your reply, thank you

**Comment by Lhumd** [comment]
Hi,
1. We only tested this code on Linux 18.04 LTS.
2. To run this code on simulation, you don't need ROS. We have ROS despondency for running the package on the robot.
3. You should see the following folder: install build log in the workspace folder. Could you provide us with more details if you cannot see any file/folder?

**Comment by 1zmm** [comment]
Hello, I am so glad that you can answer my questions. The specific situation is as follows:

I don't know if this "github.com failed" is related to the lack of vpn, because we are in China.  At present, the treep command has failed. We have completed the tick instructions according to the steps, and installed the treep plugin in pycharm. My system is ubuntu20.04.2LTS.

The following file is the problem that occurs when we run the program. I marked it with a screenshot. I hope you can help us answer our doubts.  I will really appreciate you.

[Doc2.docx](https://github.com/machines-in-motion/reactive_planners/files/8420170/Doc2.docx)
