### ISSUE TITLE
The specific situation is as follows

### ISSUE THREAD

**Issue by 1zmm** [machines-in-motion/reactive_planners#17]
Hello, I am so glad that you can answer my questions. The specific situation is as follows:

I don't know if this "github.com failed" is related to the lack of vpn, because we are in China. At present, the treep command has failed. We have completed the tick instructions according to the steps, and installed the treep plugin in pycharm. My system is ubuntu20.04.2LTS.

The following file is the problem that occurs when we run the program. I marked it with a screenshot. I hope you can help us answer our doubts. I will really appreciate you.

[Doc2.docx](https://github.com/machines-in-motion/reactive_planners/files/8420170/Doc2.docx)

**Comment by Lhumd** [comment]
Hi,
I'd suggest you try to clone packages directly from Github instead of using Treep. If it's not working, maybe using VPN helps.
