### ISSUE TITLE
Things about simulation and real time experiments

### ISSUE THREAD

**Issue by laniakeawhite** [machines-in-motion/reactive_planners#18]
From youtube  i found that there is a biped robot Bolt can walk and reject disturb.
The cool things is that they make the mechanics and electronics  of Bolt totally open-sourced on github.

What i am not sure is that if i build  a Bolt,how i can control it walking like the[video] (https://www.youtube.com/watch?v=x2jYQdjT_es&t=176s)

I found that this repo can do simulation for Bolt.

So i wonder is this repo can control walking in the real world?

**Comment by Lhumd** [comment]
Generally, it is the same repo used for the video you mentioned.

You need to make sure you can estimate the CoM position and base orientation of the robot in the real world. In the simulation, these data are given by the simulator to the code. In the real world, you can use external estimation (like Vicon camera) or internal estimation (like IMU) to get these inputs to the algorithm, which are not provided in this repository.

**Comment by laniakeawhite** [comment]
i got it
