### ISSUE TITLE
Demo code for bolt fails

### ISSUE THREAD

**Issue by sofiakwok** [machines-in-motion/reactive_planners#27]
Hi, I'm trying to run the demo for bolt but it is not working (I'm using Ubuntu 20.04 and python 3.8). 
This is what I get when I run `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`

> Starting >>> googletest-distribution
  Starting >>> mpi_cmake_modules
  Starting >>> pybind11
  Finished <<< mpi_cmake_modules [0.11s]                                           
  Starting >>> bullet_utils
  Finished <<< pybind11 [0.31s]                                                     
  Finished <<< googletest-distribution [0.35s]
  Starting >>> yaml_utils
  Starting >>> real_time_tools
  Finished <<< yaml_utils [0.11s]                                                       
  Finished <<< real_time_tools [0.16s]                                                     
  Starting >>> reactive_planners
  Finished <<< reactive_planners [0.17s]                                                       
  --- stderr: bullet_utils                    
  The documentation is not being built as the mpi_cmake_modules is not found
  ---
 > Finished <<< bullet_utils [0.66s]
 Starting >>> robot_properties_bolt
 Starting >>> robot_properties_solo
 resources =  ['resources/impedance_ctrl.yaml', 'resources/odri_control_interface/bolt_humanoid_driver.yaml', 'resources/odri_control_interface/bolt_driver.yaml', 'resources/meshes/plane.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/plane.mtl', 'resources/meshes/stl/bolt_hip_fe_right_side.stl', 'resources/meshes/stl/bolt_hip_fe_left_side.stl', 'resources/meshes/stl/bolt_shoulder_fe_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_right_side.stl', 'resources/meshes/stl/bolt_foot.stl', 'resources/meshes/stl/bolt_trunk.stl', 'resources/meshes/stl/lower_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_shoulder_fe_right_side.stl', 'resources/meshes/stl/lower_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_upper_leg_right_side.stl', 'resources/meshes/stl/upper_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_body.stl', 'resources/meshes/stl/upper_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_upper_leg_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_left_side.stl', 'resources/meshes/obj/bolt_lower_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_left_side.obj', 'resources/meshes/obj/bolt_shoulder_fe_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_right_side.obj', 'resources/meshes/obj/bolt_lower_leg_left_side.obj', 'resources/meshes/obj/bolt_upper_leg_right_side.obj', 'resources/meshes/obj/bolt_trunk.obj', 'resources/meshes/obj/bolt_upper_leg_left_side.obj', 'resources/meshes/obj/bolt_body.obj', 'resources/meshes/obj/bolt_shoulder_fe_left_side.obj', 'resources/meshes/obj/bolt_foot.obj', 'resources/dynamic_graph_manager/dgm_parameters_bolt.yaml', 'resources/dynamic_graph_manager/dgm_parameters_bolt_humanoid.yaml', 'resources/xacro/bolt_humanoid.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/xacro/upper_body.xacro', 'resources/xacro/arm.xacro', 'resources/xacro/bolt_passive_ankle.urdf.xacro', 'resources/xacro/bolt_humanoid.xacro', 'resources/xacro/bolt.xacro', 'resources/xacro/bolt.urdf.xacro']
  resources =  ['resources/impedance_ctrl.yaml', 'resources/odri_control_interface/solo12_driver.yaml', 'resources/launch/dashboard.launch', 'resources/launch/bringup.launch', 'resources/launch/rviz.launch', 'resources/launch/visual_rviz.launch', 'resources/rviz/dgbullet_vs_pybullet.rviz', 'resources/rviz/solo.rviz', 'resources/rviz/display.rviz', 'resources/meshes/cube.obj', 'resources/meshes/sphere.obj', 'resources/meshes/plane.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/cylinder.obj', 'resources/meshes/plane.mtl', 'resources/meshes/stl/without_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_body.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_v2_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_v2_right_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_foot.stl', 'resources/meshes/stl/with_foot/solo_body.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems.png', 'resources/meshes/stl/solo12/solo12_hip_fe_fr.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_4.png', 'resources/meshes/stl/solo12/solo12_hip_fe_fl.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hl.stl', 'resources/meshes/stl/solo12/_solo12_visualisation_model.PDF', 'resources/meshes/stl/solo12/solo12_hip_fe_hr.stl', 'resources/meshes/stl/solo12/solo_12_base.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_2.png', 'resources/meshes/stl/solo12/solo12_upper_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_3.png', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_body.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_body.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_body.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_body.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.mtl', 'resources/srdf/solo.srdf', 'resources/dynamic_graph_manager/dgm_parameters_solo12.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_nyu.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_wireless_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8ti.yaml', 'resources/pre_generated_urdf/readme.md', 'resources/rqt/solo.perspective.in', 'resources/xacro/solo8.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/xacro/solo12.urdf.xacro']
  --- stderr: robot_properties_solo                                                               
  resources =  ['resources/impedance_ctrl.yaml', 'resources/odri_control_interface/solo12_driver.yaml', 'resources/launch/dashboard.launch', 'resources/launch/bringup.launch', 'resources/launch/rviz.launch', 'resources/launch/visual_rviz.launch', 'resources/rviz/dgbullet_vs_pybullet.rviz', 'resources/rviz/solo.rviz', 'resources/rviz/display.rviz', 'resources/meshes/cube.obj', 'resources/meshes/sphere.obj', 'resources/meshes/plane.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/cylinder.obj', 'resources/meshes/plane.mtl', 'resources/meshes/stl/without_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/without_foot/solo_body.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_v2_left_side.stl', 'resources/meshes/stl/without_foot/solo_lower_leg_v2_right_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_left_side.stl', 'resources/meshes/stl/with_foot/solo_lower_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_upper_leg_right_side.stl', 'resources/meshes/stl/with_foot/solo_foot.stl', 'resources/meshes/stl/with_foot/solo_body.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems.png', 'resources/meshes/stl/solo12/solo12_hip_fe_fr.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_4.png', 'resources/meshes/stl/solo12/solo12_hip_fe_fl.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_hip_fe_hl.stl', 'resources/meshes/stl/solo12/_solo12_visualisation_model.PDF', 'resources/meshes/stl/solo12/solo12_hip_fe_hr.stl', 'resources/meshes/stl/solo12/solo_12_base.stl', 'resources/meshes/stl/solo12/solo12_upper_leg_right_side.stl', 'resources/meshes/stl/solo12/solo12_lower_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_2.png', 'resources/meshes/stl/solo12/solo12_upper_leg_left_side.stl', 'resources/meshes/stl/solo12/solo12_coordinate_systems_3.png', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/without_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_body.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_body.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/without_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/without_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_lower_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_body.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_body.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.mtl', 'resources/meshes/obj/with_foot/solo_upper_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_lower_leg_left_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.obj', 'resources/meshes/obj/with_foot/solo_upper_leg_right_side.mtl', 'resources/meshes/obj/with_foot/solo_foot.mtl', 'resources/srdf/solo.srdf', 'resources/dynamic_graph_manager/dgm_parameters_solo12.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_nyu.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo12_wireless_mpi_is.yaml', 'resources/dynamic_graph_manager/dgm_parameters_solo8ti.yaml', 'resources/pre_generated_urdf/readme.md', 'resources/rqt/solo.perspective.in', 'resources/xacro/solo8.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/xacro/solo12.urdf.xacro']
  
 > building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
 > building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
 > building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo8.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo8.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_solo/src/robot_properties_solo/resources/xacro/solo12.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_solo/build/lib/robot_properties_solo/resources/urdf/solo12.urdf )
  ---
 > Finished <<< robot_properties_solo [1.04s]
  --- stderr: robot_properties_bolt
  resources =  ['resources/impedance_ctrl.yaml', 'resources/odri_control_interface/bolt_humanoid_driver.yaml', 'resources/odri_control_interface/bolt_driver.yaml', 'resources/meshes/plane.obj', 'resources/meshes/checker_blue.png', 'resources/meshes/plane.mtl', 'resources/meshes/stl/bolt_hip_fe_right_side.stl', 'resources/meshes/stl/bolt_hip_fe_left_side.stl', 'resources/meshes/stl/bolt_shoulder_fe_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_right_side.stl', 'resources/meshes/stl/bolt_foot.stl', 'resources/meshes/stl/bolt_trunk.stl', 'resources/meshes/stl/lower_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_shoulder_fe_right_side.stl', 'resources/meshes/stl/lower_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_upper_leg_right_side.stl', 'resources/meshes/stl/upper_leg_200mm_right_side.stl', 'resources/meshes/stl/bolt_body.stl', 'resources/meshes/stl/upper_leg_200mm_left_side.stl', 'resources/meshes/stl/bolt_upper_leg_left_side.stl', 'resources/meshes/stl/bolt_lower_leg_left_side.stl', 'resources/meshes/obj/bolt_lower_leg_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_left_side.obj', 'resources/meshes/obj/bolt_shoulder_fe_right_side.obj', 'resources/meshes/obj/bolt_hip_fe_right_side.obj', 'resources/meshes/obj/bolt_lower_leg_left_side.obj', 'resources/meshes/obj/bolt_upper_leg_right_side.obj', 'resources/meshes/obj/bolt_trunk.obj', 'resources/meshes/obj/bolt_upper_leg_left_side.obj', 'resources/meshes/obj/bolt_body.obj', 'resources/meshes/obj/bolt_shoulder_fe_left_side.obj', 'resources/meshes/obj/bolt_foot.obj', 'resources/dynamic_graph_manager/dgm_parameters_bolt.yaml', 'resources/dynamic_graph_manager/dgm_parameters_bolt_humanoid.yaml', 'resources/xacro/bolt_humanoid.urdf.xacro', 'resources/xacro/plane_with_restitution.urdf.xacro', 'resources/xacro/leg.xacro', 'resources/xacro/upper_body.xacro', 'resources/xacro/arm.xacro', 'resources/xacro/bolt_passive_ankle.urdf.xacro', 'resources/xacro/bolt_humanoid.xacro', 'resources/xacro/bolt.xacro', 'resources/xacro/bolt.urdf.xacro']
  
 > building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_humanoid.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_humanoid.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_humanoid.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_humanoid.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_humanoid.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_humanoid.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_humanoid.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_humanoid.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/plane_with_restitution.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/plane_with_restitution.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt_passive_ankle.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt_passive_ankle.urdf )
  building xacro file ( /home/sofia/bolt_step/workspace/src/robot_properties_bolt/src/robot_properties_bolt/resources/xacro/bolt.urdf.xacro ) into ( /home/sofia/bolt_step/workspace/build/robot_properties_bolt/build/lib/robot_properties_bolt/resources/urdf/bolt.urdf )
  ---
 > Finished <<< robot_properties_bolt [1.11s]
  Starting >>> mim_control
  Finished <<< mim_control [0.15s]                      
  
 > Summary: 10 packages finished [2.40s]
    3 packages had stderr output: bullet_utils robot_properties_bolt robot_properties_solo

I source install/setup.bash, and this is what I get when I run `python3 src/reactive_planners/demos/demo_reactive_planners_bolt_step_adjustment.py`

  > pybullet build time: May 20 2022 19:44:17
  /home/sofia/bolt_step/workspace/install/robot_properties_bolt/lib/python3.8/site-packages/robot_properties_bolt/resources/urdf/bolt_humanoid.urdf
  startThreads creating 1 threads.
  starting thread 0
  started thread 0 
  argc=2
  argv[0] = --unused
  argv[1] = --start_demo_name=Physics Server
  ExampleBrowserThreadFunc started
  X11 functions dynamically loaded using dlopen/dlsym OK!
  X11 functions dynamically loaded using dlopen/dlsym OK!
  Creating context
  Created GL 3.3 context
  Direct GLX rendering context obtained
  Making context current
  GL_VENDOR=nouveau
  GL_RENDERER=NV136
  GL_VERSION=4.3 (Core Profile) Mesa 21.2.6
  GL_SHADING_LANGUAGE_VERSION=4.30
  pthread_getconcurrency()=0
  Version = 4.3 (Core Profile) Mesa 21.2.6
  Vendor = nouveau
  Renderer = NV136
  b3Printf: Selected demo: Physics Server
  startThreads creating 1 threads.
  starting thread 0
  started thread 0 
  MotionThreadFunc thread started
  ven = nouveau
  ven = nouveau
  Error: DynamicallyConsistentEndEffectorTrajectory::compute(): failed to solve the QP.
  DynamicallyConsistentEndEffectorTrajectory::compute -> the minimization problem has no solution!
  numActiveThreads = 0
  stopping threads
  Thread with taskId 0 exiting
  Thread TERMINATED
  destroy semaphore
  semaphore destroyed
  destroy main semaphore
  main semaphore destroyed
  finished
  numActiveThreads = 0
  btShutDownExampleBrowser stopping threads
  Thread with taskId 0 exiting
  Thread TERMINATED
  destroy semaphore
  semaphore destroyed
  destroy main semaphore
  main semaphore destroyed

**Comment by Lhumd** [comment]
Hi @sofiakwok,

Can you describe what you see in the simulation? Do you see the robot walking? Does it fall?

**Comment by sofiakwok** [comment]
The robot starts its trotting gait, does that for about 5 seconds, and then the window suddenly exits. I've also tried the ubuntu20.04 branch with the same results.

**Comment by Lhumd** [comment]
That's what suppose to happen. It closes the simulation after 5 sec. You can change this parameter in the code.

I am going to close this issue.
