### ISSUE TITLE
Does only can fetch the slack variables  only when QP find the solution?

### ISSUE THREAD

**Issue by laniakeawhite** [machines-in-motion/reactive_planners#28]
int the file:
https://github.com/machines-in-motion/reactive_planners/blob/master/src/dynamically_consistent_end_effector_trajectory.cpp#L583
```c++
        slack_variables_ << x_opt_(nb_var_ - 6), x_opt_(nb_var_ - 5),
            x_opt_(nb_var_ - 4);
```
it seems that always fetch the slack variables even QP has no solution.

Should put it into the brace like following？
```c++
 else
        {
            // Extract the information from the solution.
            x_opt_.resize(nb_var_);
            x_opt_ = qp_solver_.result();
            for (int i = 0; i < nb_local_sampling_time_; i++)
            {
                forces(i * 3) = x_opt_[i];
                forces(i * 3 + 1) = x_opt_[nb_local_sampling_time_ + i];
                forces(i * 3 + 2) = x_opt_[2 * nb_local_sampling_time_ + i];
            }
             slack_variables_ << x_opt_(nb_var_ - 6), x_opt_(nb_var_ - 5),
            x_opt_(nb_var_ - 4);
        }
```

**Comment by laniakeawhite** [comment]
BTW,DynamicallyConsistentEndEffectorTrajectory will call QP two times.
1. one time is in **DynamicallyConsistentEndEffectorTrajectory::compute**
2. another time is in **DynamicallyConsistentEndEffectorTrajectory::get_forces**

Does it necessary?

**Comment by Lhumd** [comment]
> int the file: https://github.com/machines-in-motion/reactive_planners/blob/master/src/dynamically_consistent_end_effector_trajectory.cpp#L583
> 
> ```c++
>         slack_variables_ << x_opt_(nb_var_ - 6), x_opt_(nb_var_ - 5),
>             x_opt_(nb_var_ - 4);
> ```
> 
> it seems that always fetch the slack variables even QP has no solution.
> 
> Should put it into the brace like following？
> 
> ```c++
>  else
>         {
>             // Extract the information from the solution.
>             x_opt_.resize(nb_var_);
>             x_opt_ = qp_solver_.result();
>             for (int i = 0; i < nb_local_sampling_time_; i++)
>             {
>                 forces(i * 3) = x_opt_[i];
>                 forces(i * 3 + 1) = x_opt_[nb_local_sampling_time_ + i];
>                 forces(i * 3 + 2) = x_opt_[2 * nb_local_sampling_time_ + i];
>             }
>              slack_variables_ << x_opt_(nb_var_ - 6), x_opt_(nb_var_ - 5),
>             x_opt_(nb_var_ - 4);
>         }
> ```

Hi,
As far as I remember, the idea was, in case we don't find the solution, to use the previous solution, which is in `x_opt_`. So, the slack variables could be as line 583 in the current code. If you put it inside the if you would avoid the reputation of `slack_variables_ << x_opt_(nb_var_ - 6), x_opt_(nb_var_ - 5), x_opt_(nb_var_ - 4);` of for case that solver fails. But it shouldn't affect the result.

**Comment by Lhumd** [comment]
> BTW,DynamicallyConsistentEndEffectorTrajectory will call QP two times.
> 
> 1. one time is in **DynamicallyConsistentEndEffectorTrajectory::compute**
> 2. another time is in **DynamicallyConsistentEndEffectorTrajectory::get_forces**
> 
> Does it necessary?

Those are two different functions. It was a software architecture choice to separate those functions to make it more modular.

I am going to close this issue. Feel free to open it if you have more questions.
